### ISSUE TITLE
[BUG] Cursor and keyboard disappearing when switching Workspace

### ISSUE THREAD

**Issue by eljejer** [mylinuxforwork/hyprland-starter#2]
I have installed Hyprland Starter 1.0 on a fresh Manjaro KDE Plasma installation.
I login from tty and execute 'Hyprland'
WS 1 has focus
I open a terminal Super+Enter
I open Firefox Super+b
I move Firefox to WS 2 Super+Shift+2
Here, unlike the default behavior, the focus is not given to WS 2
Both the keyboard and mouse cursor are "gone" until I bring focus back to WS 1, which is not possible in full screen Firefox, because no mouse cursor and keyboard, but IS possible when Firefox not full screen and I can click the WS number 1 again

**Comment by mylinuxforwork** [comment]
Thanks for testing. Can you share your hardware setup? Especially your CPU.

**Comment by mylinuxforwork** [comment]
This should work. Interesting.
Can you try to remove all environment variables in hypr/conf/environments.conf and reboot?

**Comment by eljejer** [comment]
> This should work. Interesting. Can you try to remove all environment variables in hypr/conf/environments.conf and reboot?

- unfortunately I have installed ML4W Dotfiles on top of your new installation ML4W Hyprland Starter 1.0 on github
- so I presume it's not a reliable installation as such to tackle ML4W Hyprland Starter 1.0 issues
- however, the matter of "disappearing" cursor and keyboard happens on my current installation as well
- with regards to your suggestion to remove the environment variables and reboot, I have the following situation:
-  you refer to "hypr/conf/environments.conf". This file is not present on my installation
- I do have $HOME/dotfiles/hypr/conf/environment.conf. Is this file equivalent to the one you mention? 
- If equivalent, the in this file ~/dotfiles/hypr/conf/environments/default.conf is sourced
- in this file no environment variables are set, but a reference is made to "Set in ml4w.conf"
- in this file ml4w.conf I have disabled all 'env = ' commands and rebooted

**Comment by eljejer** [comment]
> This should work. Interesting. Can you try to remove all environment variables in hypr/conf/environments.conf and reboot?

- unfortunately I have installed ML4W Dotfiles on top of your new installation ML4W Hyprland Starter 1.0 on github
- so I presume it's not a reliable installation as such to tackle ML4W Hyprland Starter 1.0 issues
- however, the matter of "disappearing" cursor and keyboard happens on my current installation as well
- with regards to your suggestion to remove the environment variables and reboot, I have the following situation:
-  you refer to "hypr/conf/environments.conf". This file is not present on my installation
- I do have $HOME/dotfiles/hypr/conf/environment.conf. Is this file equivalent to the one you mention? 
- If equivalent, the in this file ~/dotfiles/hypr/conf/environments/default.conf is sourced
- in this file no environment variables are set, but a reference is made to "Set in ml4w.conf"
- in this file ml4w.conf I have disabled all 'env = ' commands and rebooted

**Comment by eljejer** [comment]
Checking after disabling en rebooting:

- command 'env' still returns variables that have been disabled in $HOME/dotfiles/hypr/conf/ml4w.conf and I am not sure where these can be set at the moment
- the issue of disappearing cursor and keyboard remains as well

What can I do further to tackle this?

**Comment by mylinuxforwork** [comment]
Ok. You're using the Hyprland Dotfiles and not the Starter. In that case I would suggest tonrun the installer again to generate all files again. Then reboot.

Then add this to the dotfiles/hypr/conf/environments/default.conf

`env = WLR_NO_HARDWARE_CURSORS, 1`

Check this article too...

https://stackoverflow.com/questions/76289339/hyprland-mouse-icon-disappears-after-application-start

Hope this helps.

**Comment by eljejer** [comment]
> Ok. You're using the Hyprland Dotfiles and not the Starter. In that case I would suggest tonrun the installer again to generate all files again. Then reboot.
> 
> Then add this to the dotfiles/hypr/conf/environments/default.conf
> 
> `env = WLR_NO_HARDWARE_CURSORS, 1`
> 
> Check this article too...
> 
> https://stackoverflow.com/questions/76289339/hyprland-mouse-icon-disappears-after-application-start
> 
> Hope this helps.

Hello again,

Unfortunately, after re-installing and rebooting, the suggested variable setting does not prevent the cursor from disappearing.

`> echo $WLR_NO_HARDWARE_CURSORS

1`

I have set some debug variables also:

`x echo $disable_logs

false`

`~
> echo $enable_stdout_logs

true`


I ran 'Hyprland 2> error.txt 1> output.txt' and uploaded the log files to pastebin:

[error.txt](https://pastebin.com/cfMcmHmn)

[output.txt](https://pastebin.com/Y1gMmwZZ)

Could you shed a light on this further please?

**Comment by mylinuxforwork** [comment]
And the cursor never appears on other workspaces except 1? Do you have auto-hide cursor enabled somewhere in the hyprland configuration?

**Comment by eljejer** [comment]
> And the cursor never appears on other workspaces except 1? Do you have auto-hide cursor enabled somewhere in the hyprland configuration?

Turns out that the cursor only disappears on WS 2.
I can switch to WS 3, 4 & 5 using Super=3,4 or 5.
Only when entering Super 2, the cursor disappears.
I have not changed the hyprland configuration with regards to auto-hide cursor no.
Also, move a window to another WS, I can do using Super+Shift+n. Here also except Super+Shift+2.

I have tried different waybar themes and all suffer from this inactive WS 2 it seems.
Could you look into that? I have tried to find the config file which deals with initializing the (default) 5 workspaces, but could not find it...

**Comment by mylinuxforwork** [comment]
This is really strange. Cannot replicate the issue.
You can try to experiment with the workspaces module in this file:

https://github.com/mylinuxforwork/hyprland-starter/blob/main/dotfiles/.config/waybar/modules.json

You can find the documentation here:
https://github.com/Alexays/Waybar/wiki/Module:-Hyprland

**Comment by eljejer** [comment]
> This is really strange. Cannot replicate the issue. You can try to experiment with the workspaces module in this file:
> 
> https://github.com/mylinuxforwork/hyprland-starter/blob/main/dotfiles/.config/waybar/modules.json
> 
> You can find the documentation here: https://github.com/Alexays/Waybar/wiki/Module:-Hyprland

Thanks for the hint.
Also, can you try to change the default number of workspaces from 5 to 1?
When I do this, from the ML4W Dotfiles settings app, WS2 is persisitent (keeps showing) in the Waybar. 
Is this not the case at your end?

**Comment by mylinuxforwork** [comment]
In that case I would suggest you to create your own modules.conf and protect the file with a hook.sh It is described in the wiki.

**Comment by eljejer** [comment]
> In that case I would suggest you to create your own modules.conf and protect the file with a hook.sh It is described in the wiki.

I do not have modules.conf.
I do have ~/dotfiles/waybar/modules.json
Is it this one you mean?

**Comment by eljejer** [comment]
> In that case I would suggest you to create your own modules.conf and protect the file with a hook.sh It is described in the wiki.

Ypu mention modules.conf, but I presume .json, right?

What about the missing "," in

line 25 & 44 ~/dotfiles/waybar/themes/starter/modules.json
line 27 & 46 ~/dotfiles/waybar/modules.json

**Comment by mylinuxforwork** [comment]
Yes. I mean  ~/dotfiles/waybar/modules.json

**Comment by mylinuxforwork** [comment]
Cannot find the misding , Everything looks fine in the modules file.

**Comment by eljejer** [comment]
> Cannot find the missing , Everything looks fine in the modules file.

Thanks for looking into this. But can you lower the number of workspaces to 1 and then nr 2 is also gone? With me nr 2 remains when Iower the number of workspaces to 1...🤔

**Comment by eljejer** [comment]
B.t w. not only does the cursor disappear as stated in [this](https://github.com/mylinuxforwork/hyprland-starter/issues/2#issuecomment-2234365254) comment, but I stay on the current workspace as well. So pressing Super+2 while in WS 1, 3, 4 or 5 results in both the cursor disappearing and having the current WS keep focus. Also, at present time, I CAN keep using the keyboard (pressing Super+<n> after switching to WS 2. As opposed to the original title of the issue. I do remember that when browser is in full screen in the current WS (n not being WS 2) and I want to switch to WS 2, then also the keyboard is not reacting. I will check this once more...
Also, you changing the issue title by adding "Bug", do this mean that you can replicate?

**Comment by mylinuxforwork** [comment]
No. I still cannot replicate it. Really don't know how to support you here.

**Comment by eljejer** [comment]
Solved at last; turns out that on my system (laptop with integrated Intel Arc Graphics) some rogue output is created.
`hyprctl monitors` is reporting it as "Monitor Unknown-1 (ID 1)".
Disabled the rogue monitor in ~/hypr/conf/custom.conf with `monitor=Unknown-1,disable`
All good now

**Comment by eljejer** [comment]
@mylinuxforwork maybe remove label 'to be confirmed'?

**Comment by mylinuxforwork** [comment]
Great. Good to read that you could fix it.
