### ISSUE TITLE
[BUG] Config Error on hyprland.conf and decoration.conf on Garuda Linux

### ISSUE THREAD

**Issue by nimizu** [mylinuxforwork/hyprland-starter#32]
i am getting config error in hyprland.conf and decoration.conf

source= globbing error: found no match

config option <decoration:drop_shadow> does not exist etc.
i am using Garuda Linux
how to fix it here's the screenshot
![20241122_17h39m41s_grim](https://github.com/user-attachments/assets/1aeb08d5-e508-45e3-8fa0-aa0aeb412d88)

**Comment by Wand44** [comment]
![image](https://github.com/user-attachments/assets/8201ad13-f661-4254-9efc-d3d8d8d55cbc)
I have the same issue. I'm on arch btw) Tried updating and reinstalling everything, it went from "(8 more...)" to "(3 more...)" but didn't go away completely

**Comment by nimizu** [comment]
new Dotfiles are Sick and Cool. but it also got so complex.

when dot

**Comment by nimizu** [comment]
sorry i mistakenly thought what that "Close with comment" button is. and thought it will close the isse when i will comment so i clicked on it change and it insted closed the issue instead of changing when the issue is not solved yet. i am sorry. I am getting clumsier. anxiety kills me

**Comment by nimizu** [comment]
@Wand44  i fixed the decoration error by 

https://github.com/mylinuxforwork/hyprland-starter/commit/217828d6e26b3c3b69076b89dad06457b00e6526#diff-c6866339922b1f2f24cc205ce71bef649f92a49e2ef44750b4309cce28056488R14

replacing this code. now i only have souce= gobbling error
![20241123_23h04m34s_grim](https://github.com/user-attachments/assets/acb1343e-bce8-4046-9352-397e2c32ec72)

**Comment by Wand44** [comment]
![image](https://github.com/user-attachments/assets/658b3635-5cba-483e-88c3-c9b91ee95638)
yep, it fixes everything, thank you. Now just have to revert to the previous version, i liked the old rofi better.
