### ISSUE TITLE
[BUG] Can't open Settings app

### ISSUE THREAD

**Issue by skyred50** [mylinuxforwork/hyprland-starter#4]
Traceback (most recent call last):
  File "/tmp/.mount_ML4W_Hkadg5a/usr/bin/ml4w-hyprland-settings.py", line 10, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by mylinuxforwork** [comment]
Thanks for testing. What's your distro? And current desktop environment?

Not all dependencies are installed at the moment.

**Comment by skyred50** [comment]
Arch Linux no DE just Hyprland

**Comment by mylinuxforwork** [comment]
Can you install

`sudo pacman -S python-gobject gtk4`

Reboot and try again?

**Comment by skyred50** [comment]
It works now, I was missing python-gobject.

**Comment by skyred50** [comment]
It works now, I was missing python-gobject.

**Comment by mylinuxforwork** [comment]
Thanks for testing. Will add this package to the installer.
