### ISSUE TITLE
[FEATURE] Test on Nobara

### ISSUE THREAD

**Issue by mylinuxforwork** [mylinuxforwork/hyprland-starter#6]
**Is your feature request related to a problem? Please describe.**
Received a request on YouTube to check the compatibility on Nobara Linux.

**Describe the solution you'd like**
Setup a VM and install Nobara.

**Additional context**
https://nobaraproject.org/

**Comment by ILLnar-Nizami** [comment]
so I've tried to install it on Nobara 40 (VM via QEMU). The script stopped executing with an error message:
Your Linux  distribution is not supported

**Comment by mylinuxforwork** [comment]
Because I test for the Distro Name. And Nobara is not supported. 

You can try this. Open the folder Downloads/hyprland-starter and run 

`./install.sh fedora`

Will test tomorrow as well.

**Comment by mylinuxforwork** [comment]
@ILLnar-Nizami  I have just released the 1.0.1 incl. Nobara support. Would be great if you could test. I could install it successfully in my VM.

**Comment by mylinuxforwork** [comment]
@ILLnar-Nizami I have added 2560x1600 to the installation script.
